freebsd_instance:
  cpu: 1
  memory: 1G

task:
  matrix:
    - name: snapshots/amd64/13.5-STABLE
      freebsd_instance:
        image_family: freebsd-13-5-snap
    - name: snapshots/amd64/14.3-STABLE
      freebsd_instance:
        image_family: freebsd-14-3-snap
    - name: snapshots/amd64/15.0-STABLE
      freebsd_instance:
        image_family: freebsd-15-0-amd64-ufs-snap
    - name: releases/amd64/13.5-RELEASE
      freebsd_instance:
        image_family: freebsd-13-5
    - name: releases/amd64/14.3-RELEASE
      freebsd_instance:
        image_family: freebsd-14-3
    - name: releases/amd64/15.0-RELEASE
      freebsd_instance:
        image_family: freebsd-15-0-amd64-ufs
  stateful: false
  tests_file:
    path: tests.lua
    from_contents: |
      f = io.open('/dev/echo0', 'w+')
      f:write('hello!')
      f:flush()
      assert(f:read(6) == 'hello!')
      assert(f:read(12) == 'hello!hello!')
      f:close()
  setup_script: pkg install -y chez-scheme
  load_script: kldload -n cuse
  echo_background_script: chez-scheme echo.ss
  # Give the script a second to start.
  wait_script: test -c /dev/echo0 || sleep 1
  test_script: /usr/libexec/flua tests.lua
